-- -- https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#sumneko_lua
-- require('lspconfig').sumneko_lua.setup {
--   on_attach = function()
--     on_attach()
--     vim.cmd [[autocmd BufWritePre <buffer> lua require'stylua-nvim'.format_file()]]
--   end,
--   settings = {
--     Lua = {
--       runtime = {
--         version = 'LuaJIT',
--         path = runtime_path,
--       },
--       diagnostics = {
--         globals = { 'vim' },
--       },
--       workspace = {
--         library = vim.api.nvim_get_runtime_file('', true),
--         checkThirdParty = false, -- THIS IS THE IMPORTANT LINE TO ADD
--       },
--       telemetry = {
--         enable = false,
--       },
--     },
--   },
-- })
